"""empty message

Revision ID: 46fe9adb00be
Revises: ef45d0c271c2
Create Date: 2020-05-29 01:00:07.115147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fe9adb00be'
down_revision = 'ef45d0c271c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
